version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres_miagepoule
    environment:
      POSTGRES_DB: miagepoule
      POSTGRES_USER: miageuser
      POSTGRES_PASSWORD: miagepassword
    ports:
      - "5433:5432"
    networks:
      - miage-network
    restart: unless-stopped
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - miage-network
  # API Spring Boot
  poule-api:
    build:
      context: ./KernelService
      dockerfile: Dockerfile
    container_name: spring_miagepoule
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/miagepoule
      SPRING_DATASOURCE_USERNAME: miageuser
      SPRING_DATASOURCE_PASSWORD: miagepassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8083:8082"
    depends_on:
      - postgres
    networks:
      - miage-network
    restart: unless-stopped

  # API Spring Boot
  gateway-api:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: spring_miagepoule_gateway
    ports:
      - "8081:8081"
    depends_on:
      - poule-api
    networks:
      - miage-network
    restart: unless-stopped

  # Frontend
  frontend:
    build: ./front
    container_name: react_miagepoule
    ports:
      - "3000:3000"  # Un seul port exposé
    networks:
      - miage-network
    restart: unless-stopped

  cypress:
    image: cypress/included:13.6.0
    container_name: cypress_miagepoule
    working_dir: /e2e
    volumes:
      - ./:/e2e
    depends_on:
      - frontend
    networks:
      - miage-network
    command:  cypress open --project /e2e

volumes:
  postgres_data:
  cerberus_mysql_data:

networks:
  miage-network:
    driver: bridge