spring.application.name=spring-gateway
server.port=8081

# Monolithe unique derrière la gateway
service.backend.url=http://poule-api:8082

security.jwt.secret=votreTresLongSecretQuiFaitPlusDe32CaracteresPourJWT256bits12345

# Logging pour déboguer
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG