spring.application.name=spring-gateway
server.port=8080

# Monolithe unique derrière la gateway
service.backend.url=http://localhost:8081

# Utilisateur de dev (si Spring Security basique)
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=USER
