spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/miagepoule
    username: miageuser
    password: miagepassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      connection-timeout: 20000
      minimum-idle: 5


  # properties for email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: no.reply.miagepoule@gmail.com
    password: wavk ztdd ssoi jwvq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always
      continue-on-error: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  main:
    allow-bean-definition-overriding: true

server:
  port: 8082

security:
  jwt:
    secret: votreTresLongSecretQuiFaitPlusDe32CaracteresPourJWT256bits12345
    expiration-ms : 3600000

app:
  encryption:
    enabled: true
    master-key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

  storage:
    max-file-size: 10485760 # 10MB
    allowed-content-types: application/pdf,image/jpeg,image/png,image/jpg
    max-documents-per-user: 50
