spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/miagepoule
    username: miageuser
    password: miagepassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always
      continue-on-error: true

server:
  port: 8082

security:
  jwt:
    secret: votreTresLongSecretQuiFaitPlusDe32CaracteresPourJWT256bits12345
    expiration-ms : 3600000